#line 2 "/home/danil/CLionProjects/F77Ccompiler/src/f77lexer.c"

#line 4 "/home/danil/CLionProjects/F77Ccompiler/src/f77lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 80
#define YY_END_OF_BUFFER 81
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[332] =
    {   0,
        0,    0,    0,    0,    0,    0,   81,   79,    2,   79,
       79,    3,   80,   78,    5,    4,    5,   78,   78,   78,
       78,   19,   20,   17,   14,   22,   15,   78,   18,   24,
       23,   21,   77,   77,   77,   77,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,   77,    2,
        0,    0,    3,    4,    0,    0,    0,   37,    0,   30,
        0,   36,    0,    0,    0,   16,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,   24,    0,    0,   77,
        0,   77,   77,   77,   77,   77,   77,   56,   77,   77,
       77,   77,   77,   77,   51,   77,   77,    0,   27,   77,

       77,   77,   77,   77,   77,   77,   77,   77,    0,    0,
        0,    0,    3,    0,    0,   37,    0,   36,   36,    0,
       36,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,    0,    0,   25,    0,   24,    0,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   76,   77,   77,
       77,    0,   77,   77,   77,    0,   77,   77,   77,   77,
       77,   77,   77,   77,   77,   77,   77,   77,    0,    0,
        0,    3,    0,    0,    0,    0,   38,    0,    0,   41,
       40,   43,   42,   39,    0,    0,   46,    0,    0,    0,
        0,   24,   26,   77,    7,   64,   77,   77,   77,   77,

       77,   52,    0,   77,   77,   74,   77,   77,    0,   65,
       77,   77,   28,   72,   77,   77,   77,   77,   70,    8,
       77,   66,   77,   54,   77,   77,   31,   33,    0,    3,
       29,   32,   34,   45,   47,    0,    0,   44,    0,   49,
        0,   25,   24,   59,   77,   73,   77,   77,   77,    0,
       77,    0,    0,   57,   55,   77,   77,   65,   77,   77,
       77,   67,   71,   77,   77,   77,   58,   69,    1,    0,
       48,   35,   25,   77,   77,   77,   77,    0,   53,   57,
       55,   68,   77,   77,   77,   77,   77,   61,   77,    0,
       25,   77,   10,   77,    0,   53,   77,    6,   12,   77,

       77,   77,   77,   60,    0,    0,   62,   77,    0,   77,
       13,    0,    0,   50,    0,   77,    0,    0,   75,   63,
        0,    0,    0,    0,    0,    0,   11,    0,    0,    9,
        0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    7,    1,    1,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       19,   19,   19,   19,   19,   19,   20,   21,    1,    1,
       22,    1,    1,    1,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   35,   36,   37,   38,
       39,   40,   41,   42,   43,   44,   45,   46,   47,   48,
        1,   49,    1,    1,   50,    1,   51,   52,   53,   54,

       55,   56,   57,   58,   59,   32,   60,   61,   62,   63,
       64,   65,   66,   67,   68,   69,   70,   71,   72,   73,
       74,   75,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[76] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    2,    2,    2,
        1,    1,    3,    3,    3,    3,    3,    3,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    1,    5,
        3,    3,    3,    3,    3,    3,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4
    } ;

static const flex_int16_t yy_base[346] =
    {   0,
        0,    4,    0,    0,   57,    0,  601,  802,  802,    2,
        6,   13,  802,  802,  802,  802,    9,   23,  127,    0,
      169,  802,  802,  577,  802,  802,  802,  203,  802,  119,
      802,  802,    0,  132,  120,   98,  119,  174,  104,  147,
      105,  190,  162,    1,  121,  184,  211,  574,  569,  802,
       31,  538,   19,  802,   37,  535,  152,  529,  213,    0,
        6,  519,  271,  148,  244,  802,  164,  195,  192,  208,
      259,  219,  208,  213,  220,   25,  285,  317,  329,    0,
       29,  254,  223,  272,  259,  278,  282,  287,  291,  259,
      304,  310,  315,  312,    0,  310,  326,   31,  130,  329,

      318,  331,  340,  316,  340,  339,  338,  339,    0,    0,
       48,  515,  354,  473,  155,  354,  383,  367,  368,  359,
      379,  397,  367,  381,  365,  412,  409,  407,  397,  391,
      360,  386,  364,  370,  436,  400,  430,  427,  388,  396,
      399,  398,  417,  421,  419,  412,  439,  466,  440,  434,
      446,  464,  436,  447,  444,  464,  441,  456,  437,  448,
      451,  467,  444,  451,  469,  474,  478,  471,  313,  311,
      148,  512,  475,  492,  494,  272,  802,  258,  478,  802,
      802,  802,  802,  802,  478,  253,  802,  496,  221,  536,
      545,  549,  802,  501,    0,    0,  501,  515,  510,  516,

      524,  556,  568,  536,  546,    0,  553,  536,  542,    0,
      551,  556,  802,    0,  548,  557,  544,  549,    0,    0,
      550,    0,  554,    0,  565,  566,  802,  802,  156,  802,
      802,  802,  802,  802,  802,  568,  197,  802,  155,  802,
      611,  615,  802,    0,  571,    0,  570,  575,  571,  610,
      591,  599,  609,    0,    0,  597,  609,  802,  615,  620,
      617,    0,    0,  622,  612,  606,    0,    0,  267,  129,
      802,  802,  633,  612,  609,  613,   50,  618,    0,  802,
      802,    0,  620,  618,  625,  618,  626,    0,  620,  304,
      802,  637,    0,  640,  652,  802,  643,    0,    0,  653,

       12,  660,  653,    0,  657,  656,    0,  657,    0,  662,
        0,  664,  673,    0,    0,  674,  665,  679,    0,    0,
      673,  678,  683,  671,  667,  683,  802,  679,  682,  802,
      802,  745,  750,  755,  759,  762,  766,  771,  776,  781,
      786,  790,  792,  793,  796
    } ;

static const flex_int16_t yy_def[346] =
    {   0,
      332,  332,  333,  333,  331,    5,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  334,  335,
      336,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  331,
      331,  338,  331,  331,  331,  339,  334,  331,  340,  335,
      336,  331,  336,   63,  341,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  337,
      331,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  331,  337,  337,

      337,  337,  337,  337,  337,  337,  337,  337,  342,  343,
      331,  338,  331,  339,  334,  334,  340,  331,  331,  336,
      336,  341,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  337,  337,
      337,  331,  337,  337,  337,  331,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  342,  343,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  337,  337,  337,  337,  337,  337,  337,

      337,  337,  331,  337,  337,  337,  337,  337,  331,  337,
      337,  337,  331,  337,  337,  337,  337,  337,  337,  337,
      337,  337,  337,  337,  337,  337,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  337,  337,  337,  337,  337,  337,  331,
      337,  331,  331,  337,  337,  337,  337,  331,  337,  337,
      337,  337,  337,  337,  337,  337,  337,  337,  331,  331,
      331,  331,  331,  337,  337,  337,  337,  331,  337,  331,
      331,  337,  337,  337,  337,  337,  337,  337,  337,  331,
      331,  337,  337,  337,  331,  331,  337,  337,  337,  337,

      337,  337,  337,  337,  331,  331,  337,  337,  344,  337,
      337,  331,  331,  337,  345,  337,  331,  331,  345,  337,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
        0,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331
    } ;

static const flex_int16_t yy_nxt[878] =
    {   0,
      331,  331,    9,   10,   50,   51,    9,   10,   50,   52,
       11,   54,   55,   62,   11,  309,   12,   12,   12,   12,
       12,   12,   12,   12,   11,   54,   56,  103,   11,   53,
       53,   53,   53,   50,  111,  113,  113,  113,  113,   54,
       55,  135,  135,  135,  135,  138,  138,  156,  156,  156,
       50,  171,   11,  295,   65,  103,   11,   14,   15,   16,
       17,   18,   19,   20,   21,   22,   23,   24,   25,   26,
       27,   28,   29,   30,   30,   30,   30,   31,   32,   33,
       34,   35,   36,   37,   38,   39,   33,   40,   33,   33,
       41,   33,   33,   42,   43,   33,   44,   45,   46,   33,

       33,   47,   48,   33,   49,   14,   14,   33,   34,   35,
       36,   37,   38,   39,   33,   40,   33,   41,   33,   33,
       42,   43,   33,   44,   45,   46,   33,   33,   47,   48,
       33,   49,   58,   76,   88,   77,   77,   77,   77,   81,
       94,   97,   84,  272,   78,   79,   99,   99,   99,   85,
       50,  229,   89,   86,   90,  119,   87,   58,   50,  269,
       58,   88,  104,  105,   64,   64,   64,   94,   97,  272,
       84,   82,   78,   79,   95,   59,   62,   85,   83,   89,
       86,   90,   96,   87,  101,   63,   63,   63,   64,  104,
      105,   64,   64,   64,   64,   64,   64,   98,   82,  123,

       59,  102,   95,   59,   91,   83,   99,   99,   99,   96,
       92,  271,  101,  106,  125,   57,   93,   65,  116,   64,
       64,   64,   64,   64,   64,   67,  123,  100,  102,   68,
       69,   70,   91,  124,  126,  240,   71,   92,   72,   73,
      107,  106,  125,   93,   74,  130,   61,  132,   75,  127,
      108,  121,  133,   67,  100,  131,  134,   68,   69,   70,
      124,  117,  126,   71,  140,   72,   73,  238,  107,   50,
      290,   74,  235,  130,  132,   75,  127,  108,  118,  133,
      139,  142,  131,  134,  148,  128,  234,   63,   63,   63,
       64,  140,  122,   64,   64,   64,   64,   64,   64,   76,

      129,   77,   77,   77,   77,  141,   50,  290,  139,  142,
       78,   79,  148,  128,  143,  152,  144,  145,  228,   65,
      227,   64,   64,   64,   64,   64,   64,  129,  136,  146,
      136,  147,  141,  137,  137,  137,  137,  149,   78,   79,
      136,  143,  136,  144,  145,  137,  137,  137,  137,  150,
      151,  154,  164,  153,  155,  157,  146,  158,  147,  116,
      159,  160,  162,  165,  149,  166,   62,  161,  167,  168,
      172,  172,  172,  172,   61,   61,  150,  151,  154,  164,
      153,  163,  155,  157,  158,   57,  121,  159,  116,  160,
      162,  165,  176,  166,  161,  177,  167,  168,  179,   61,

      187,  186,   59,  173,  121,  184,  188,   65,  163,  189,
      194,  183,  174,  174,  175,  175,  137,  137,  137,  137,
      176,  182,  195,  181,  178,  179,  180,   65,  186,  185,
      173,  117,  196,  188,  193,  201,  189,  197,  194,  174,
      174,  175,  175,  138,  138,  122,  192,  192,  192,  192,
      195,  178,  135,  135,  135,  135,  185,  198,  199,  196,
      200,  190,  191,  201,  197,  202,  206,  152,  207,  203,
      208,  213,  210,  211,  212,   54,  214,  216,  215,  218,
      156,  156,  156,  217,  198,  199,  221,  200,  222,  190,
      191,  204,  219,  202,  206,  207,  205,  231,  208,  210,

      220,  211,  212,  214,  216,  209,  215,  218,  223,  224,
      217,  225,  226,  221,  232,  222,  233,   50,  236,  204,
      219,  237,  239,  245,  205,  231,   61,  220,  230,  230,
      230,  230,  209,  244,   57,  223,  224,   54,  225,  226,
       50,  246,  232,  247,  233,  236,  248,  241,  237,  241,
      239,  245,  242,  242,  242,  242,  241,  249,  241,  250,
      244,  242,  242,  242,  242,  243,  243,  243,  243,  246,
      247,  203,  254,  255,  248,  256,  110,  257,  258,  259,
      260,  109,  261,  262,  249,  263,  251,   66,  264,  265,
      266,  267,  268,  252,  270,  274,  275,  277,  253,  254,

      331,  255,  331,  256,  257,  258,  331,  259,  260,  261,
      276,  262,  263,  250,  251,  264,  265,  266,  279,  267,
      268,  252,  270,  274,  275,  277,  253,  242,  242,  242,
      242,  273,  273,  273,  273,  280,  281,  276,  282,  283,
      278,  284,  285,  286,  287,  296,  279,  288,  289,  291,
      291,  291,  291,  292,  293,  294,  297,  298,  299,  300,
      301,  302,  280,  303,  281,  282,  304,  283,  278,  284,
      285,  286,  287,  296,  288,  289,  305,  331,  307,  308,
      292,  293,  294,  297,  298,  299,  300,  301,  302,  306,
      310,  303,  311,  312,  304,  313,  314,  316,  317,  318,

      320,  331,  321,  322,  305,  307,  323,  308,  324,  325,
      331,  326,  327,  328,  331,  329,  306,  330,  310,  311,
      312,  331,  313,  314,  316,  317,  331,  318,  320,  321,
      331,  322,  331,  323,  331,  331,  324,  325,  326,  327,
      331,  328,  329,  331,  330,    8,    8,    8,    8,    8,
       13,   13,   13,   13,   13,   57,   57,   57,   57,   57,
       60,   60,   61,   61,   61,   61,   61,   80,   80,   80,
       80,  112,  112,  112,  112,  112,  114,  114,  114,  114,
      114,  115,  115,  115,  115,  115,  120,  120,  120,  120,
      120,  169,  169,  170,  170,  315,  315,  319,  319,  319,

      319,    7,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331
    } ;

static const flex_int16_t yy_chk[878] =
    {   0,
        0,    0,    1,    1,   10,   10,    2,    2,   11,   11,
        1,   17,   17,   61,    2,  301,    1,    1,    1,    1,
        2,    2,    2,    2,    1,   18,   18,   44,    2,   12,
       12,   12,   12,   51,   51,   53,   53,   53,   53,   55,
       55,   76,   76,   76,   76,   81,   81,   98,   98,   98,
      111,  111,    1,  277,   61,   44,    2,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,

        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,   19,   30,   36,   30,   30,   30,   30,   34,
       39,   41,   35,  270,   30,   30,   99,   99,   99,   35,
      171,  171,   37,   35,   37,   64,   35,   57,  229,  229,
      115,   36,   45,   45,   64,   64,   64,   39,   41,  239,
       35,   34,   30,   30,   40,   19,   21,   35,   34,   37,
       35,   37,   40,   35,   43,   21,   21,   21,   21,   45,
       45,   21,   21,   21,   21,   21,   21,   42,   34,   67,

       57,   43,   40,  115,   38,   34,   42,   42,   42,   40,
       38,  237,   43,   46,   69,   59,   38,   21,   59,   21,
       21,   21,   21,   21,   21,   28,   67,   42,   43,   28,
       28,   28,   38,   68,   70,  189,   28,   38,   28,   28,
       47,   46,   69,   38,   28,   72,   65,   73,   28,   70,
       47,   65,   74,   28,   42,   72,   75,   28,   28,   28,
       68,   59,   70,   28,   83,   28,   28,  186,   47,  269,
      269,   28,  178,   72,   73,   28,   70,   47,   63,   74,
       82,   85,   72,   75,   90,   71,  176,   63,   63,   63,
       63,   83,   65,   63,   63,   63,   63,   63,   63,   77,

       71,   77,   77,   77,   77,   84,  290,  290,   82,   85,
       77,   77,   90,   71,   86,   94,   87,   87,  170,   63,
      169,   63,   63,   63,   63,   63,   63,   71,   78,   88,
       78,   89,   84,   78,   78,   78,   78,   91,   77,   77,
       79,   86,   79,   87,   87,   79,   79,   79,   79,   92,
       93,   96,  104,   94,   97,  100,   88,  101,   89,  116,
      101,  102,  103,  105,   91,  106,  120,  102,  107,  108,
      113,  113,  113,  113,  118,  119,   92,   93,   96,  104,
       94,  103,   97,  100,  101,  117,  121,  101,  117,  102,
      103,  105,  123,  106,  102,  124,  107,  108,  125,  122,

      132,  131,  116,  118,  122,  130,  133,  120,  103,  134,
      139,  129,  118,  119,  118,  119,  136,  136,  136,  136,
      123,  128,  140,  127,  124,  125,  126,  121,  131,  130,
      118,  117,  141,  133,  138,  146,  134,  142,  139,  118,
      119,  118,  119,  138,  138,  122,  137,  137,  137,  137,
      140,  124,  135,  135,  135,  135,  130,  143,  144,  141,
      145,  135,  135,  146,  142,  147,  149,  152,  150,  148,
      151,  156,  153,  154,  155,  114,  157,  159,  158,  161,
      156,  156,  156,  160,  143,  144,  163,  145,  164,  135,
      135,  148,  162,  147,  149,  150,  148,  173,  151,  153,

      162,  154,  155,  157,  159,  152,  158,  161,  165,  166,
      160,  167,  168,  163,  174,  164,  175,  112,  179,  148,
      162,  185,  188,  197,  148,  173,   62,  162,  172,  172,
      172,  172,  152,  194,   58,  165,  166,   56,  167,  168,
       52,  198,  174,  199,  175,  179,  200,  190,  185,  190,
      188,  197,  190,  190,  190,  190,  191,  201,  191,  202,
      194,  191,  191,  191,  191,  192,  192,  192,  192,  198,
      199,  203,  204,  205,  200,  207,   49,  208,  209,  211,
      212,   48,  215,  216,  201,  217,  202,   24,  218,  221,
      223,  225,  226,  203,  236,  245,  247,  249,  203,  204,

        7,  205,    0,  207,  208,  209,    0,  211,  212,  215,
      248,  216,  217,  250,  202,  218,  221,  223,  251,  225,
      226,  203,  236,  245,  247,  249,  203,  241,  241,  241,
      241,  242,  242,  242,  242,  252,  253,  248,  256,  257,
      250,  259,  260,  261,  264,  278,  251,  265,  266,  273,
      273,  273,  273,  274,  275,  276,  283,  284,  285,  286,
      287,  289,  252,  292,  253,  256,  294,  257,  250,  259,
      260,  261,  264,  278,  265,  266,  295,    0,  297,  300,
      274,  275,  276,  283,  284,  285,  286,  287,  289,  295,
      302,  292,  303,  305,  294,  306,  308,  310,  312,  313,

      316,    0,  317,  318,  295,  297,  321,  300,  322,  323,
        0,  324,  325,  326,    0,  328,  295,  329,  302,  303,
      305,    0,  306,  308,  310,  312,    0,  313,  316,  317,
        0,  318,    0,  321,    0,    0,  322,  323,  324,  325,
        0,  326,  328,    0,  329,  332,  332,  332,  332,  332,
      333,  333,  333,  333,  333,  334,  334,  334,  334,  334,
      335,  335,  336,  336,  336,  336,  336,  337,  337,  337,
      337,  338,  338,  338,  338,  338,  339,  339,  339,  339,
      339,  340,  340,  340,  340,  340,  341,  341,  341,  341,
      341,  342,  342,  343,  343,  344,  344,  345,  345,  345,

      345,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[81] =
    {   0,
0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0,     };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
#line 2 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
#include <string>
#include "f77parser.h"
using namespace std;
#line 784 "/home/danil/CLionProjects/F77Ccompiler/src/f77lexer.c"

#line 786 "/home/danil/CLionProjects/F77Ccompiler/src/f77lexer.c"

#define INITIAL 0
#define PROGRAM_ENDS 1
#define STMT 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

        static int yy_start_stack_ptr = 0;
        static int yy_start_stack_depth = 0;
        static int *yy_start_stack = NULL;
    
    static void yy_push_state ( int _new_state );
    
    static void yy_pop_state ( void );
    
    static int yy_top_state ( void );
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 15 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"

#line 1017 "/home/danil/CLionProjects/F77Ccompiler/src/f77lexer.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 332 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 802 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 16 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{
	if(YY_START != STMT){
		BEGIN(STMT);
	}
}
	YY_BREAK
/* comments, empty string and newline */
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 22 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._str = string(strdup(yytext));return COMMENT;}
	YY_BREAK
/*label statement*/
case 3:
YY_RULE_SETUP
#line 24 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{
	BEGIN(STMT);
	yylval._constant = new constant_node(new complex_type(integer), replace_all(string(strdup(yytext)), " ", ""));
	return NUMBER;
}
	YY_BREAK
case 4:
/* rule 4 can match eol */
YY_RULE_SETUP
#line 29 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{
	BEGIN(INITIAL);
	yylval._str = string(strdup(yytext));
	return COMMENT;
}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 34 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{}
	YY_BREAK
case 6:
#line 36 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
case 7:
#line 37 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
case 8:
#line 38 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
case 9:
#line 39 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
case 10:
#line 40 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
case 11:
#line 41 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
case 12:
#line 42 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
case 13:
YY_RULE_SETUP
#line 42 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._type = parse_type(yytext);return TYPE;}
	YY_BREAK
/* operators */
case 14:
YY_RULE_SETUP
#line 44 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return ADD;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 45 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return MINUS;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 46 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return POW;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 47 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return MUL;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 48 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return DIV;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 49 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return LEFT_PARENT;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 50 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return RIGHT_PARENT;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 51 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return EQUAL;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 52 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return COMMA;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 53 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return COLON;}
	YY_BREAK
/* numerical constants */
case 24:
YY_RULE_SETUP
#line 55 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._constant = new constant_node(new complex_type(integer), replace_all(string(strdup(yytext)), "d", "e")); return NUMBER;}
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 56 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._constant = new constant_node(new complex_type(real), replace_all(string(strdup(yytext)), "d", "e")); return NUMBER;}
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 57 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._constant = new constant_node(new complex_type(integer), binary_string_to_int(substring(string(strdup(yytext)), 2, -2))); return NUMBER;}
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 58 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._constant = new constant_node(new complex_type(integer), "0" + substring(string(strdup(yytext)), 1, -1)); return NUMBER;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 59 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._constant = new constant_node(new complex_type(integer),"0" + substring(string(strdup(yytext)), 2, -2)); return NUMBER;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 60 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._constant = new constant_node(new complex_type(integer), "0" + substring(string(strdup(yytext)), 1, -4)); return NUMBER;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 61 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._constant = new constant_node(new complex_type(integer),"0x" + substring(string(strdup(yytext)), 1, -1)); return NUMBER;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 62 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._constant = new constant_node(new complex_type(integer), "0x" + substring(string(strdup(yytext)), 2, -2)); return NUMBER;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 63 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._constant = new constant_node(new complex_type(integer), "0x" + substring(string(strdup(yytext)), 1, -4)); return NUMBER;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 64 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._constant = new constant_node(new complex_type(integer),"0x" + substring(string(strdup(yytext)), 2, -2)); return NUMBER;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 65 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._constant = new constant_node(new complex_type(integer), "0x" + substring(string(strdup(yytext)), 1, -4)); return NUMBER;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 66 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._constant = new constant_node(new complex_type(boolean), parse_bool(yytext));return NUMBER;}
	YY_BREAK
/* describe string*/
case 36:
/* rule 36 can match eol */
YY_RULE_SETUP
#line 68 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._constant = new constant_node(new complex_type(chars), "\"" + replace_all(replace_all(substring(string(strdup(yytext)), 1, -2), "\\", "\\\\"), "''", "'") + "\"");return CHARS;}
	YY_BREAK
case 37:
/* rule 37 can match eol */
YY_RULE_SETUP
#line 69 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._constant = new constant_node(new complex_type(chars), "\"" + replace_all(replace_all(substring(string(strdup(yytext)), 1, -2), "\\", "\\\\"), "\"\"", "\\\"") + "\"" );return CHARS;}
	YY_BREAK
/* comparison operators */
case 38:
YY_RULE_SETUP
#line 71 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._str = "==";return CMP;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 72 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._str = "!=";return CMP;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 73 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._str = ">";return CMP;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 74 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._str = ">=";return CMP;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 75 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._str = "<";return CMP;}
	YY_BREAK
case 43:
YY_RULE_SETUP
#line 76 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._str = "<=";return CMP;}
	YY_BREAK
/* logical operators */
case 44:
YY_RULE_SETUP
#line 78 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._str = "~";return NOT;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 79 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._str = "&";return AND;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 80 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._str = "|";return OR;}
	YY_BREAK
case 47:
YY_RULE_SETUP
#line 81 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._str = "&";return EQV;}
	YY_BREAK
case 48:
#line 83 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
case 49:
YY_RULE_SETUP
#line 83 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._str = "^";return XOR;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 84 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return PARAM;}
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 85 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return IF;} /* statements */
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 86 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return ELSE;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 87 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return ELSEIF;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 88 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return THEN;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 89 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return ENDIF;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 90 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return DO;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 91 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return ENDDO;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 92 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return WHILE;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 93 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return BREAK;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 94 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return CONTINUE;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 95 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return RETURN;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 96 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return FUNCTION;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 97 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return SUBROUTINE;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 98 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return CALL;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 99 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return GOTO;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 100 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return STOP;}
	YY_BREAK
case 67:
YY_RULE_SETUP
#line 101 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return PAUSE;}
	YY_BREAK
/* input / output */
case 68:
YY_RULE_SETUP
#line 103 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return FORMAT;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 104 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return WRITE;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 105 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return READ;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 106 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return PRINT;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 107 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return OPEN;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 108 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return CLOSE;}
	YY_BREAK
case 74:
YY_RULE_SETUP
#line 109 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return AFILE;}
	YY_BREAK
/* main program units */
case 75:
YY_RULE_SETUP
#line 111 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return PROGRAM;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 112 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return END;}
	YY_BREAK
case 77:
YY_RULE_SETUP
#line 113 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._str = string(strdup(yytext)); return SYMNAME;}
	YY_BREAK
/*tabs and space*/
case 78:
YY_RULE_SETUP
#line 115 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{}
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 116 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{}
	YY_BREAK
/*end of file*/
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STMT):
#line 118 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{ BEGIN(PROGRAM_ENDS); return END_OF_FILE; }
	YY_BREAK
case YY_STATE_EOF(PROGRAM_ENDS):
#line 119 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{ return 0; }
	YY_BREAK
case 80:
YY_RULE_SETUP
#line 120 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
ECHO;
	YY_BREAK
#line 1496 "/home/danil/CLionProjects/F77Ccompiler/src/f77lexer.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 332 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 332 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 331);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

    static void yy_push_state (int  _new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc( new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

    static void yy_pop_state  (void)
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    static int yy_top_state  (void)
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_start_stack_ptr) = 0;
    (yy_start_stack_depth) = 0;
    (yy_start_stack) =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Destroy the start condition stack. */
        yyfree( (yy_start_stack)  );
        (yy_start_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 120 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"

