#line 2 "/home/danil/CLionProjects/F77Ccompiler/src/f77lexer.c"

#line 4 "/home/danil/CLionProjects/F77Ccompiler/src/f77lexer.c"

#define  YY_INT_ALIGNED short int

/* A lexical scanner generated by flex */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 6
#define YY_FLEX_SUBMINOR_VERSION 4
#if YY_FLEX_SUBMINOR_VERSION > 0
#define FLEX_BETA
#endif

/* First, we deal with  platform-specific or compiler-specific issues. */

/* begin standard C headers. */
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <stdlib.h>

/* end standard C headers. */

/* flex integer type definitions */

#ifndef FLEXINT_H
#define FLEXINT_H

/* C99 systems have <inttypes.h>. Non-C99 systems may or may not. */

#if defined (__STDC_VERSION__) && __STDC_VERSION__ >= 199901L

/* C99 says to define __STDC_LIMIT_MACROS before including stdint.h,
 * if you want the limit (max/min) macros for int types. 
 */
#ifndef __STDC_LIMIT_MACROS
#define __STDC_LIMIT_MACROS 1
#endif

#include <inttypes.h>
typedef int8_t flex_int8_t;
typedef uint8_t flex_uint8_t;
typedef int16_t flex_int16_t;
typedef uint16_t flex_uint16_t;
typedef int32_t flex_int32_t;
typedef uint32_t flex_uint32_t;
#else
typedef signed char flex_int8_t;
typedef short int flex_int16_t;
typedef int flex_int32_t;
typedef unsigned char flex_uint8_t; 
typedef unsigned short int flex_uint16_t;
typedef unsigned int flex_uint32_t;

/* Limits of integral types. */
#ifndef INT8_MIN
#define INT8_MIN               (-128)
#endif
#ifndef INT16_MIN
#define INT16_MIN              (-32767-1)
#endif
#ifndef INT32_MIN
#define INT32_MIN              (-2147483647-1)
#endif
#ifndef INT8_MAX
#define INT8_MAX               (127)
#endif
#ifndef INT16_MAX
#define INT16_MAX              (32767)
#endif
#ifndef INT32_MAX
#define INT32_MAX              (2147483647)
#endif
#ifndef UINT8_MAX
#define UINT8_MAX              (255U)
#endif
#ifndef UINT16_MAX
#define UINT16_MAX             (65535U)
#endif
#ifndef UINT32_MAX
#define UINT32_MAX             (4294967295U)
#endif

#ifndef SIZE_MAX
#define SIZE_MAX               (~(size_t)0)
#endif

#endif /* ! C99 */

#endif /* ! FLEXINT_H */

/* begin standard C++ headers. */

/* TODO: this is always defined, so inline it */
#define yyconst const

#if defined(__GNUC__) && __GNUC__ >= 3
#define yynoreturn __attribute__((__noreturn__))
#else
#define yynoreturn
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an
 *   integer in range [0..255] for use as an array index.
 */
#define YY_SC_TO_UI(c) ((YY_CHAR) (c))

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN (yy_start) = 1 + 2 *
/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START (((yy_start) - 1) / 2)
#define YYSTATE YY_START
/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)
/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin  )
#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#ifndef YY_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k.
 * Moreover, YY_BUF_SIZE is 2*YY_READ_BUF_SIZE in the general case.
 * Ditto for the __ia64__ case accordingly.
 */
#define YY_BUF_SIZE 32768
#else
#define YY_BUF_SIZE 16384
#endif /* __ia64__ */
#endif

/* The state buf must be large enough to hold one state per character in the main buffer.
 */
#define YY_STATE_BUF_SIZE   ((YY_BUF_SIZE + 2) * sizeof(yy_state_type))

#ifndef YY_TYPEDEF_YY_BUFFER_STATE
#define YY_TYPEDEF_YY_BUFFER_STATE
typedef struct yy_buffer_state *YY_BUFFER_STATE;
#endif

#ifndef YY_TYPEDEF_YY_SIZE_T
#define YY_TYPEDEF_YY_SIZE_T
typedef size_t yy_size_t;
#endif

extern int yyleng;

extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2
    
    /* Note: We specifically omit the test for yy_rule_can_match_eol because it requires
     *       access to the local variable yy_act. Since yyless() is a macro, it would break
     *       existing scanners that call yyless() from OUTSIDE yylex.
     *       One obvious solution it to make yy_act a global. I tried that, and saw
     *       a 5% performance hit in a non-yylineno scanner, because yy_act is
     *       normally declared as a register variable-- so it is not worth it.
     */
    #define  YY_LESS_LINENO(n) \
            do { \
                int yyl;\
                for ( yyl = n; yyl < yyleng; ++yyl )\
                    if ( yytext[yyl] == '\n' )\
                        --yylineno;\
            }while(0)
    #define YY_LINENO_REWIND_TO(dst) \
            do {\
                const char *p;\
                for ( p = yy_cp-1; p >= (dst); --p)\
                    if ( *p == '\n' )\
                        --yylineno;\
            }while(0)
    
/* Return all but the first "n" matched characters back to the input stream. */
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		*yy_cp = (yy_hold_char); \
		YY_RESTORE_YY_MORE_OFFSET \
		(yy_c_buf_p) = yy_cp = yy_bp + yyless_macro_arg - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )
#define unput(c) yyunput( c, (yytext_ptr)  )

#ifndef YY_STRUCT_YY_BUFFER_STATE
#define YY_STRUCT_YY_BUFFER_STATE
struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	int yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

    int yy_bs_lineno; /**< The line count. */
    int yy_bs_column; /**< The column count. */

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;

#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2

	};
#endif /* !YY_STRUCT_YY_BUFFER_STATE */

/* Stack of input buffers. */
static size_t yy_buffer_stack_top = 0; /**< index of top of stack. */
static size_t yy_buffer_stack_max = 0; /**< capacity of stack. */
static YY_BUFFER_STATE * yy_buffer_stack = NULL; /**< Stack as an array. */

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 *
 * Returns the top of the stack, or NULL.
 */
#define YY_CURRENT_BUFFER ( (yy_buffer_stack) \
                          ? (yy_buffer_stack)[(yy_buffer_stack_top)] \
                          : NULL)
/* Same as previous macro, but useful when we know that the buffer stack is not
 * NULL or when we need an lvalue. For internal use only.
 */
#define YY_CURRENT_BUFFER_LVALUE (yy_buffer_stack)[(yy_buffer_stack_top)]

/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;
static int yy_n_chars;		/* number of characters read into yy_ch_buf */
int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = NULL;
static int yy_init = 0;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart ( FILE *input_file  );
void yy_switch_to_buffer ( YY_BUFFER_STATE new_buffer  );
YY_BUFFER_STATE yy_create_buffer ( FILE *file, int size  );
void yy_delete_buffer ( YY_BUFFER_STATE b  );
void yy_flush_buffer ( YY_BUFFER_STATE b  );
void yypush_buffer_state ( YY_BUFFER_STATE new_buffer  );
void yypop_buffer_state ( void );

static void yyensure_buffer_stack ( void );
static void yy_load_buffer_state ( void );
static void yy_init_buffer ( YY_BUFFER_STATE b, FILE *file  );
#define YY_FLUSH_BUFFER yy_flush_buffer( YY_CURRENT_BUFFER )

YY_BUFFER_STATE yy_scan_buffer ( char *base, yy_size_t size  );
YY_BUFFER_STATE yy_scan_string ( const char *yy_str  );
YY_BUFFER_STATE yy_scan_bytes ( const char *bytes, int len  );

void *yyalloc ( yy_size_t  );
void *yyrealloc ( void *, yy_size_t  );
void yyfree ( void *  );

#define yy_new_buffer yy_create_buffer
#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){ \
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_is_interactive = is_interactive; \
	}
#define yy_set_bol(at_bol) \
	{ \
	if ( ! YY_CURRENT_BUFFER ){\
        yyensure_buffer_stack (); \
		YY_CURRENT_BUFFER_LVALUE =    \
            yy_create_buffer( yyin, YY_BUF_SIZE ); \
	} \
	YY_CURRENT_BUFFER_LVALUE->yy_at_bol = at_bol; \
	}
#define YY_AT_BOL() (YY_CURRENT_BUFFER_LVALUE->yy_at_bol)

/* Begin user sect3 */

#define yywrap() (/*CONSTCOND*/1)
#define YY_SKIP_YYWRAP
typedef flex_uint8_t YY_CHAR;

FILE *yyin = NULL, *yyout = NULL;

typedef int yy_state_type;

extern int yylineno;
int yylineno = 1;

extern char *yytext;
#ifdef yytext_ptr
#undef yytext_ptr
#endif
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state ( void );
static yy_state_type yy_try_NUL_trans ( yy_state_type current_state  );
static int yy_get_next_buffer ( void );
static void yynoreturn yy_fatal_error ( const char* msg  );

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	(yytext_ptr) = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	(yy_hold_char) = *yy_cp; \
	*yy_cp = '\0'; \
	(yy_c_buf_p) = yy_cp;
#define YY_NUM_RULES 79
#define YY_END_OF_BUFFER 80
/* This struct is not used in this scanner,
   but its presence is necessary. */
struct yy_trans_info
	{
	flex_int32_t yy_verify;
	flex_int32_t yy_nxt;
	};
static const flex_int16_t yy_accept[326] =
    {   0,
        0,    0,    0,    0,    0,    0,   80,   78,    1,    2,
       78,   78,   79,   77,    4,    3,    4,   77,   77,   77,
       77,   32,   33,   30,   27,   35,   28,   77,   31,   13,
       36,   34,   76,   76,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,   76,   76,   76,    2,
        0,    0,    3,    0,    0,    0,   26,    0,   19,    0,
       25,    0,    0,    0,   29,   13,    0,    0,    0,    0,
        0,    0,    0,    0,    0,    0,    0,    0,   76,    0,
       76,   76,   76,   76,   76,   76,   55,   76,   76,   76,
       76,   76,   76,   50,   76,   76,    0,   16,   76,   76,

       76,   76,   76,   76,   76,   76,   76,    0,    0,    0,
        0,    0,    0,   26,    0,   25,   25,    0,   25,    0,
        0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
        0,    0,   14,    0,   13,    0,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   75,   76,   76,   76,    0,
       76,   76,   76,    0,   76,   76,   76,   76,   76,   76,
       76,   76,   76,   76,   76,   76,    0,    0,    1,    0,
        0,    0,    0,   37,    0,    0,   40,   39,   42,   41,
       38,    0,    0,   45,    0,    0,    0,    0,   13,   15,
       76,    6,   63,   76,   76,   76,   76,   76,   51,    0,

       76,   76,   73,   76,   76,    0,   64,   76,   76,   17,
       71,   76,   76,   76,   76,   69,    7,   76,   65,   76,
       53,   76,   76,   20,   22,    0,   18,   21,   23,   44,
       46,    0,    0,   43,    0,   48,    0,   14,   13,   58,
       76,   72,   76,   76,   76,    0,   76,    0,    0,   56,
       54,   76,   76,   64,   76,   76,   76,   66,   70,   76,
       76,   76,   57,   68,    0,   47,   24,   14,   76,   76,
       76,   76,    0,   52,   56,   54,   67,   76,   76,   76,
       76,   76,   60,   76,   14,   76,    9,   76,    0,   52,
       76,    5,   11,   76,   76,   76,   76,   59,    0,    0,

       61,   76,    0,   76,   12,    0,    0,   49,    0,   76,
        0,    0,   74,   62,    0,    0,    0,    0,    0,    0,
       10,    0,    0,    8,    0
    } ;

static const YY_CHAR yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    4,    5,    6,    1,    7,    1,    1,    8,    9,
       10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
       19,   19,   19,   19,   19,   19,   20,   21,    1,    1,
       22,    1,    1,    1,   23,   24,   25,   26,   27,   28,
       29,   30,   31,   32,   33,   34,   35,   36,   37,   38,
       39,   40,   41,   42,   43,   44,   45,   46,   47,   48,
        1,   49,    1,    1,   50,    1,   51,   52,   53,   54,

       55,   56,   57,   58,   59,   32,   60,   61,   62,   63,
       64,   65,   66,   67,   68,   69,   70,   71,   72,   73,
       74,   75,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,

        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static const YY_CHAR yy_meta[76] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    2,    2,    2,    2,
        1,    1,    3,    3,    3,    3,    3,    3,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    1,    5,
        3,    3,    3,    3,    3,    3,    4,    4,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    4,
        4,    4,    4,    4,    4
    } ;

static const flex_int16_t yy_base[340] =
    {   0,
        0,    3,    0,    0,   56,    0,  560,  789,  789,  789,
        5,    7,  789,  789,  789,  789,    9,   11,  126,    0,
      168,  789,  789,   13,    1,  789,   12,  202,  789,  118,
      789,  789,    0,  131,  119,   97,  118,  173,  103,  146,
      104,  189,  161,    0,  120,  183,  210,  508,  465,  789,
       19,  464,  789,   30,  453,  151,  789,  212,    0,  150,
      408,  270,   18,  243,  789,  284,  197,  196,  191,  258,
      278,  218,  207,  209,  215,   21,   30,  317,    0,   28,
      229,  222,  246,  258,  277,  280,  274,  277,  286,  294,
      290,  296,  304,    0,  306,  320,  129,  147,  323,  313,

      323,  328,  321,  337,  335,  332,  333,    0,    0,   48,
      412,  411,  154,  220,  362,  358,  359,  344,  361,  368,
      346,  359,  347,  384,  369,  291,  271,  373,  344,  268,
      351,  356,  409,  423,  427,  401,  397,  397,  364,  398,
      408,  412,  409,  429,  427,  453,  428,  423,  434,  433,
      424,  435,  435,  452,  432,  449,  433,  450,  451,  463,
      448,  454,  453,  460,  464,  457,  264,  262,  147,  480,
      481,  482,  252,  789,  219,  468,  789,  789,  789,  789,
      789,  466,  196,  789,  479,  154,  526,  535,  510,  789,
      481,    0,    0,  488,  495,  481,  504,  487,  547,  553,

      519,  530,    0,  536,  519,  525,    0,  535,  540,  789,
        0,  532,  541,  528,  531,    0,    0,  532,    0,  536,
        0,  547,  548,  789,  789,  398,  789,  789,  789,  789,
      789,  549,  144,  789,  140,  789,  591,  596,  789,    0,
      552,    0,  563,  559,  564,  597,  589,  583,  593,    0,
        0,  581,  593,  789,  598,  603,  600,    0,    0,  606,
      595,  589,    0,    0,  128,  789,  789,  616,  595,  592,
      596,   50,  612,    0,  789,  789,    0,  605,  603,  610,
      604,  613,    0,  609,  789,  633,    0,  634,  638,  789,
      631,    0,    0,  635,   39,  641,  634,    0,  640,  639,

        0,  640,    0,  645,    0,  647,  656,    0,    0,  657,
      648,  662,    0,    0,  658,  662,  668,  656,  652,  668,
      789,  665,  669,  789,  789,  732,  737,  742,  746,  749,
      753,  758,  763,  768,  773,  777,  779,  780,  783
    } ;

static const flex_int16_t yy_def[340] =
    {   0,
      326,  326,  327,  327,  325,    5,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  328,  329,
      330,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  325,
      325,  332,  325,  325,  333,  328,  325,  334,  329,  330,
      325,  330,   62,  335,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  331,  325,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  325,  331,  331,  331,

      331,  331,  331,  331,  331,  331,  331,  336,  337,  325,
      332,  333,  328,  328,  334,  325,  325,  330,  330,  335,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  325,
      331,  331,  331,  325,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  331,  331,  336,  337,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  325,

      331,  331,  331,  331,  331,  325,  331,  331,  331,  325,
      331,  331,  331,  331,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  331,
      331,  331,  331,  331,  331,  325,  331,  325,  325,  331,
      331,  331,  331,  325,  331,  331,  331,  331,  331,  331,
      331,  331,  331,  331,  325,  325,  325,  325,  331,  331,
      331,  331,  325,  331,  325,  325,  331,  331,  331,  331,
      331,  331,  331,  331,  325,  331,  331,  331,  325,  325,
      331,  331,  331,  331,  331,  331,  331,  331,  325,  325,

      331,  331,  338,  331,  331,  325,  325,  331,  339,  331,
      325,  325,  339,  331,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,    0,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325
    } ;

static const flex_int16_t yy_nxt[865] =
    {   0,
      325,    9,   10,   11,    9,   10,   11,   50,   51,   50,
       52,   53,   54,   53,   55,   53,   55,   66,   66,   66,
       66,   50,  110,   65,   12,  117,  102,   12,   66,   66,
       66,   66,   53,   54,   63,   63,   63,  133,  133,  133,
      133,  134,  303,  134,  136,  136,  135,  135,  135,  135,
       50,  169,   12,  289,  102,   12,   14,   15,   16,   17,
       18,   19,   20,   21,   22,   23,   24,   25,   26,   27,
       28,   29,   30,   30,   30,   30,   31,   32,   33,   34,
       35,   36,   37,   38,   39,   33,   40,   33,   33,   41,
       33,   33,   42,   43,   33,   44,   45,   46,   33,   33,

       47,   48,   33,   49,   14,   14,   33,   34,   35,   36,
       37,   38,   39,   33,   40,   33,   41,   33,   33,   42,
       43,   33,   44,   45,   46,   33,   33,   47,   48,   33,
       49,   57,   76,   87,   66,   66,   66,   66,   80,   93,
       96,   83,  267,   77,   78,  154,  154,  154,   84,   50,
      226,   88,   85,   89,  267,   86,   57,   61,  266,   57,
       87,  103,  104,   98,   98,   98,   93,   96,  236,   83,
       81,   77,   78,   94,   58,   61,   84,   82,   88,   85,
       89,   95,   86,  100,   62,   62,   62,   63,  103,  104,
       63,   63,   63,   63,   63,   63,   97,   81,   64,   58,

      101,   94,   58,   90,   82,   98,   98,   98,   95,   91,
      234,  100,  105,  123,   56,   92,   64,  114,   63,   63,
       63,   63,   63,   63,   67,   57,   99,  101,   68,   69,
       70,   90,  121,  231,  122,   71,   91,   72,   73,  106,
      105,  123,   92,   74,  128,   60,  130,   75,  131,  107,
      119,  132,   67,   99,  129,  137,   68,   69,   70,  121,
      115,  122,   71,  138,   72,   73,  230,  106,   58,  225,
       74,  224,  128,  130,   75,  131,  107,  116,  132,  139,
      140,  129,  184,  137,  124,  180,   62,   62,   62,   63,
      138,  120,   63,   63,   63,   63,   63,   63,   76,  125,

       66,   66,   66,   66,  126,  179,  139,  150,  140,   77,
       78,  146,  124,  141,  142,  143,  144,  145,   64,  127,
       63,   63,   63,   63,   63,   63,  125,  147,  134,  148,
      134,  149,  126,  135,  135,  135,  135,   77,   78,  146,
      141,  142,  143,  144,  145,  151,  127,  152,  153,  155,
      160,   61,  156,  158,  147,  157,  148,  162,  149,  159,
      163,  164,  165,  166,   56,   60,   60,  114,  119,  161,
       60,  173,  151,  174,  152,  119,  153,  155,  160,  156,
      176,  158,  157,  178,  162,  183,  159,  181,  163,  164,
      165,  166,   64,  185,  170,  186,  161,  193,  177,  173,

       50,  226,  175,  171,  171,  172,  172,  176,  190,   64,
      115,  182,  183,   53,   50,   60,  120,  136,  136,  191,
      185,  170,  186,  192,  193,  133,  133,  133,  133,  175,
      171,  171,  172,  172,  187,  188,  150,  194,  182,  135,
      135,  135,  135,  189,  189,  189,  189,  191,  195,  196,
      197,  192,  198,  199,  203,   53,  200,  204,  205,  210,
      207,  208,  187,  188,  194,  209,   50,  211,  154,  154,
      154,  212,  109,  213,  206,  195,  196,  197,  201,  215,
      198,  199,  203,  202,  204,  214,  205,  207,  216,  208,
      218,  219,  220,  209,  211,  221,  217,  222,  223,  212,

      213,  206,  227,  228,  229,  235,  201,  215,  232,  233,
      241,  202,  214,  240,  243,  108,  216,  218,  219,  220,
      245,  242,  221,  217,  222,  223,  239,  239,  239,  239,
      227,  228,  229,  235,  244,  232,  233,  237,  241,  237,
      240,  243,  238,  238,  238,  238,  237,  245,  237,  242,
      246,  238,  238,  238,  238,  250,  200,  251,  252,  325,
      253,  254,  244,  255,  256,  325,  257,  258,  325,  259,
      260,  261,  262,  263,  264,  265,  269,  247,  248,  325,
      325,  325,  250,  249,  325,  251,  252,  253,  254,  270,
      272,  255,  256,  257,  271,  258,  259,  260,  261,  262,

      246,  263,  264,  265,  269,  247,  248,  238,  238,  238,
      238,  249,  268,  268,  268,  268,  274,  270,  272,  275,
      276,  271,  277,  278,  279,  280,  281,  273,  282,  325,
      283,  284,  285,  285,  285,  285,  286,  287,  288,  290,
      325,  291,  292,  293,  274,  294,  275,  295,  276,  277,
      296,  278,  279,  280,  281,  273,  282,  283,  284,  297,
      298,  302,  299,  286,  287,  288,  301,  290,  291,  292,
      293,  304,  294,  305,  295,  300,  306,  296,  307,  308,
      310,  311,  312,  314,  325,  315,  316,  297,  298,  302,
      299,  317,  318,  301,  319,  325,  320,  321,  322,  304,

      305,  323,  300,  306,  324,  307,  308,  310,  311,  325,
      312,  314,  315,  325,  316,  325,  325,  325,  317,  325,
      318,  325,  319,  320,  321,  325,  322,  325,  323,  325,
      325,  324,    8,    8,    8,    8,    8,   13,   13,   13,
       13,   13,   56,   56,   56,   56,   56,   59,   59,   60,
       60,   60,   60,   60,   79,   79,   79,   79,  111,  111,
      111,  111,  111,  112,  112,  112,  112,  112,  113,  113,
      113,  113,  113,  118,  118,  118,  118,  118,  167,  167,
      168,  168,  309,  309,  313,  313,  313,  313,    7,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,

      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325
    } ;

static const flex_int16_t yy_chk[865] =
    {   0,
        0,    1,    1,    1,    2,    2,    2,   11,   11,   12,
       12,   17,   17,   18,   18,   24,   24,   25,   25,   25,
       25,   51,   51,   24,    1,   63,   44,    2,   27,   27,
       27,   27,   54,   54,   63,   63,   63,   76,   76,   76,
       76,   77,  295,   77,   80,   80,   77,   77,   77,   77,
      110,  110,    1,  272,   44,    2,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,

        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,    5,    5,    5,    5,    5,    5,    5,    5,    5,
        5,   19,   30,   36,   30,   30,   30,   30,   34,   39,
       41,   35,  265,   30,   30,   97,   97,   97,   35,  169,
      169,   37,   35,   37,  235,   35,   56,   60,  233,  113,
       36,   45,   45,   98,   98,   98,   39,   41,  186,   35,
       34,   30,   30,   40,   19,   21,   35,   34,   37,   35,
       37,   40,   35,   43,   21,   21,   21,   21,   45,   45,
       21,   21,   21,   21,   21,   21,   42,   34,   60,   56,

       43,   40,  113,   38,   34,   42,   42,   42,   40,   38,
      183,   43,   46,   69,   58,   38,   21,   58,   21,   21,
       21,   21,   21,   21,   28,  114,   42,   43,   28,   28,
       28,   38,   67,  175,   68,   28,   38,   28,   28,   47,
       46,   69,   38,   28,   72,   64,   73,   28,   74,   47,
       64,   75,   28,   42,   72,   81,   28,   28,   28,   67,
       58,   68,   28,   82,   28,   28,  173,   47,  114,  168,
       28,  167,   72,   73,   28,   74,   47,   62,   75,   83,
       84,   72,  130,   81,   70,  127,   62,   62,   62,   62,
       82,   64,   62,   62,   62,   62,   62,   62,   66,   70,

       66,   66,   66,   66,   71,  126,   83,   93,   84,   66,
       66,   89,   70,   85,   86,   86,   87,   88,   62,   71,
       62,   62,   62,   62,   62,   62,   70,   90,   78,   91,
       78,   92,   71,   78,   78,   78,   78,   66,   66,   89,
       85,   86,   86,   87,   88,   93,   71,   95,   96,   99,
      102,  118,  100,  101,   90,  100,   91,  103,   92,  101,
      104,  105,  106,  107,  115,  116,  117,  115,  119,  102,
      120,  121,   93,  122,   95,  120,   96,   99,  102,  100,
      123,  101,  100,  125,  103,  129,  101,  128,  104,  105,
      106,  107,  118,  131,  116,  132,  102,  139,  124,  121,

      226,  226,  122,  116,  117,  116,  117,  123,  136,  119,
      115,  128,  129,  112,  111,   61,  120,  136,  136,  137,
      131,  116,  132,  138,  139,  133,  133,  133,  133,  122,
      116,  117,  116,  117,  133,  133,  150,  140,  128,  134,
      134,  134,  134,  135,  135,  135,  135,  137,  141,  142,
      143,  138,  144,  145,  147,   55,  146,  148,  149,  154,
      151,  152,  133,  133,  140,  153,   52,  155,  154,  154,
      154,  156,   49,  157,  150,  141,  142,  143,  146,  159,
      144,  145,  147,  146,  148,  158,  149,  151,  160,  152,
      161,  162,  163,  153,  155,  164,  160,  165,  166,  156,

      157,  150,  170,  171,  172,  185,  146,  159,  176,  182,
      194,  146,  158,  191,  196,   48,  160,  161,  162,  163,
      198,  195,  164,  160,  165,  166,  189,  189,  189,  189,
      170,  171,  172,  185,  197,  176,  182,  187,  194,  187,
      191,  196,  187,  187,  187,  187,  188,  198,  188,  195,
      199,  188,  188,  188,  188,  201,  200,  202,  204,    7,
      205,  206,  197,  208,  209,    0,  212,  213,    0,  214,
      215,  218,  220,  222,  223,  232,  241,  199,  200,    0,
        0,    0,  201,  200,    0,  202,  204,  205,  206,  243,
      245,  208,  209,  212,  244,  213,  214,  215,  218,  220,

      246,  222,  223,  232,  241,  199,  200,  237,  237,  237,
      237,  200,  238,  238,  238,  238,  247,  243,  245,  248,
      249,  244,  252,  253,  255,  256,  257,  246,  260,    0,
      261,  262,  268,  268,  268,  268,  269,  270,  271,  273,
        0,  278,  279,  280,  247,  281,  248,  282,  249,  252,
      284,  253,  255,  256,  257,  246,  260,  261,  262,  286,
      288,  294,  289,  269,  270,  271,  291,  273,  278,  279,
      280,  296,  281,  297,  282,  289,  299,  284,  300,  302,
      304,  306,  307,  310,    0,  311,  312,  286,  288,  294,
      289,  315,  316,  291,  317,    0,  318,  319,  320,  296,

      297,  322,  289,  299,  323,  300,  302,  304,  306,    0,
      307,  310,  311,    0,  312,    0,    0,    0,  315,    0,
      316,    0,  317,  318,  319,    0,  320,    0,  322,    0,
        0,  323,  326,  326,  326,  326,  326,  327,  327,  327,
      327,  327,  328,  328,  328,  328,  328,  329,  329,  330,
      330,  330,  330,  330,  331,  331,  331,  331,  332,  332,
      332,  332,  332,  333,  333,  333,  333,  333,  334,  334,
      334,  334,  334,  335,  335,  335,  335,  335,  336,  336,
      337,  337,  338,  338,  339,  339,  339,  339,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,

      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325,  325,  325,  325,  325,  325,  325,
      325,  325,  325,  325
    } ;

/* Table of booleans, true if rule could match eol. */
static const flex_int32_t yy_rule_can_match_eol[80] =
    {   0,
0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 
        };

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

extern int yy_flex_debug;
int yy_flex_debug = 0;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
#line 2 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
#include <string>
#include "f77parser.h"
using namespace std;
#line 779 "/home/danil/CLionProjects/F77Ccompiler/src/f77lexer.c"

#line 781 "/home/danil/CLionProjects/F77Ccompiler/src/f77lexer.c"

#define INITIAL 0
#define PROGRAM_ENDS 1
#define STMT 2

#ifndef YY_NO_UNISTD_H
/* Special case for "unistd.h", since it is non-ANSI. We include it way
 * down here because we want the user's section 1 to have been scanned first.
 * The user has a chance to override it with an option.
 */
#include <unistd.h>
#endif

#ifndef YY_EXTRA_TYPE
#define YY_EXTRA_TYPE void *
#endif

static int yy_init_globals ( void );

/* Accessor methods to globals.
   These are made visible to non-reentrant scanners for convenience. */

int yylex_destroy ( void );

int yyget_debug ( void );

void yyset_debug ( int debug_flag  );

YY_EXTRA_TYPE yyget_extra ( void );

void yyset_extra ( YY_EXTRA_TYPE user_defined  );

FILE *yyget_in ( void );

void yyset_in  ( FILE * _in_str  );

FILE *yyget_out ( void );

void yyset_out  ( FILE * _out_str  );

			int yyget_leng ( void );

char *yyget_text ( void );

int yyget_lineno ( void );

void yyset_lineno ( int _line_number  );

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap ( void );
#else
extern int yywrap ( void );
#endif
#endif

#ifndef YY_NO_UNPUT
    
    static void yyunput ( int c, char *buf_ptr  );
    
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy ( char *, const char *, int );
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen ( const char * );
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput ( void );
#else
static int input ( void );
#endif

#endif

        static int yy_start_stack_ptr = 0;
        static int yy_start_stack_depth = 0;
        static int *yy_start_stack = NULL;
    
    static void yy_push_state ( int _new_state );
    
    static void yy_pop_state ( void );
    
    static int yy_top_state ( void );
    
/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#ifdef __ia64__
/* On IA-64, the buffer size is 16k, not 8k */
#define YY_READ_BUF_SIZE 16384
#else
#define YY_READ_BUF_SIZE 8192
#endif /* __ia64__ */
#endif

/* Copy whatever the last rule matched to the standard output. */
#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO do { if (fwrite( yytext, (size_t) yyleng, 1, yyout )) {} } while (0)
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( YY_CURRENT_BUFFER_LVALUE->yy_is_interactive ) \
		{ \
		int c = '*'; \
		int n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else \
		{ \
		errno=0; \
		while ( (result = (int) fread(buf, 1, (yy_size_t) max_size, yyin)) == 0 && ferror(yyin)) \
			{ \
			if( errno != EINTR) \
				{ \
				YY_FATAL_ERROR( "input in flex scanner failed" ); \
				break; \
				} \
			errno=0; \
			clearerr(yyin); \
			} \
		}\
\

#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* end tables serialization structures and prototypes */

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL_IS_OURS 1

extern int yylex (void);

#define YY_DECL int yylex (void)
#endif /* !YY_DECL */

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK /*LINTED*/break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

/** The main scanner function which does all the work.
 */
YY_DECL
{
	yy_state_type yy_current_state;
	char *yy_cp, *yy_bp;
	int yy_act;
    
	if ( !(yy_init) )
		{
		(yy_init) = 1;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! (yy_start) )
			(yy_start) = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! YY_CURRENT_BUFFER ) {
			yyensure_buffer_stack ();
			YY_CURRENT_BUFFER_LVALUE =
				yy_create_buffer( yyin, YY_BUF_SIZE );
		}

		yy_load_buffer_state(  );
		}

	{
#line 15 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"

#line 1012 "/home/danil/CLionProjects/F77Ccompiler/src/f77lexer.c"

	while ( /*CONSTCOND*/1 )		/* loops until end-of-file is reached */
		{
		yy_cp = (yy_c_buf_p);

		/* Support of yytext. */
		*yy_cp = (yy_hold_char);

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = (yy_start);
yy_match:
		do
			{
			YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)] ;
			if ( yy_accept[yy_current_state] )
				{
				(yy_last_accepting_state) = yy_current_state;
				(yy_last_accepting_cpos) = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 326 )
					yy_c = yy_meta[yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 789 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;

		if ( yy_act != YY_END_OF_BUFFER && yy_rule_can_match_eol[yy_act] )
			{
			int yyl;
			for ( yyl = 0; yyl < yyleng; ++yyl )
				if ( yytext[yyl] == '\n' )
					
    yylineno++;
;
			}

do_action:	/* This label is used only to access EOF actions. */

		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = (yy_hold_char);
			yy_cp = (yy_last_accepting_cpos);
			yy_current_state = (yy_last_accepting_state);
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 16 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{
	if(YY_START != STMT){
		BEGIN(STMT);
	}
}
	YY_BREAK
/* comments, empty string and newline */
case 2:
/* rule 2 can match eol */
YY_RULE_SETUP
#line 22 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._str = string(strdup(yytext));return COMMENT;}
	YY_BREAK
case 3:
/* rule 3 can match eol */
YY_RULE_SETUP
#line 23 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{BEGIN(INITIAL);yylval._str = string(strdup(yytext));return COMMENT;}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 24 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{}
	YY_BREAK
case 5:
#line 26 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
case 6:
#line 27 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
case 7:
#line 28 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
case 8:
#line 29 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
case 9:
#line 30 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
case 10:
#line 31 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
case 11:
#line 32 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
case 12:
YY_RULE_SETUP
#line 32 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._type = parse_type(yytext);return TYPE;}
	YY_BREAK
/* numerical constants */
case 13:
YY_RULE_SETUP
#line 34 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._constant = new constant_node(new complex_type(integer), replace_all(string(strdup(yytext)), "d", "e")); return NUMBER;}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 35 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._constant = new constant_node(new complex_type(real), replace_all(string(strdup(yytext)), "d", "e")); return NUMBER;}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 36 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._constant = new constant_node(new complex_type(integer), binary_string_to_int(substring(string(strdup(yytext)), 2, -2))); return NUMBER;}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 37 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._constant = new constant_node(new complex_type(integer), "0" + substring(string(strdup(yytext)), 1, -1)); return NUMBER;}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 38 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._constant = new constant_node(new complex_type(integer),"0" + substring(string(strdup(yytext)), 2, -2)); return NUMBER;}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 39 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._constant = new constant_node(new complex_type(integer), "0" + substring(string(strdup(yytext)), 1, -4)); return NUMBER;}
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 40 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._constant = new constant_node(new complex_type(integer),"0x" + substring(string(strdup(yytext)), 1, -1)); return NUMBER;}
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 41 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._constant = new constant_node(new complex_type(integer), "0x" + substring(string(strdup(yytext)), 2, -2)); return NUMBER;}
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 42 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._constant = new constant_node(new complex_type(integer), "0x" + substring(string(strdup(yytext)), 1, -4)); return NUMBER;}
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 43 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._constant = new constant_node(new complex_type(integer),"0x" + substring(string(strdup(yytext)), 2, -2)); return NUMBER;}
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 44 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._constant = new constant_node(new complex_type(integer), "0x" + substring(string(strdup(yytext)), 1, -4)); return NUMBER;}
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 45 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._constant = new constant_node(new complex_type(boolean), parse_bool(yytext));return NUMBER;}
	YY_BREAK
/* describe string*/
case 25:
/* rule 25 can match eol */
YY_RULE_SETUP
#line 47 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._constant = new constant_node(new complex_type(chars), "\"" + replace_all(substring(string(strdup(yytext)), 1, -2), "''", "'") + "\"");return CHARS;}
	YY_BREAK
case 26:
/* rule 26 can match eol */
YY_RULE_SETUP
#line 48 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._constant = new constant_node(new complex_type(chars), "\"" + substring(string(strdup(yytext)), 1, -2) + "\"" );return CHARS;}
	YY_BREAK
/* operators */
case 27:
YY_RULE_SETUP
#line 50 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return ADD;}
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 51 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return MINUS;}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 52 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return POW;}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 53 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return MUL;}
	YY_BREAK
case 31:
YY_RULE_SETUP
#line 54 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return DIV;}
	YY_BREAK
case 32:
YY_RULE_SETUP
#line 55 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return LEFT_PARENT;}
	YY_BREAK
case 33:
YY_RULE_SETUP
#line 56 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return RIGHT_PARENT;}
	YY_BREAK
case 34:
YY_RULE_SETUP
#line 57 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return EQUAL;}
	YY_BREAK
case 35:
YY_RULE_SETUP
#line 58 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return COMMA;}
	YY_BREAK
case 36:
YY_RULE_SETUP
#line 59 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return COLON;}
	YY_BREAK
/* comparison operators */
case 37:
YY_RULE_SETUP
#line 61 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._str = "==";return CMP;}
	YY_BREAK
case 38:
YY_RULE_SETUP
#line 62 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._str = "!=";return CMP;}
	YY_BREAK
case 39:
YY_RULE_SETUP
#line 63 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._str = ">";return CMP;}
	YY_BREAK
case 40:
YY_RULE_SETUP
#line 64 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._str = ">=";return CMP;}
	YY_BREAK
case 41:
YY_RULE_SETUP
#line 65 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._str = "<";return CMP;}
	YY_BREAK
case 42:
YY_RULE_SETUP
#line 66 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._str = "<=";return CMP;}
	YY_BREAK
/* logical operators */
case 43:
YY_RULE_SETUP
#line 68 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._str = "~";return NOT;}
	YY_BREAK
case 44:
YY_RULE_SETUP
#line 69 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._str = "&";return AND;}
	YY_BREAK
case 45:
YY_RULE_SETUP
#line 70 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._str = "|";return OR;}
	YY_BREAK
case 46:
YY_RULE_SETUP
#line 71 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._str = "&";return EQV;}
	YY_BREAK
case 47:
#line 73 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
case 48:
YY_RULE_SETUP
#line 73 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._str = "^";return XOR;}
	YY_BREAK
case 49:
YY_RULE_SETUP
#line 74 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return PARAM;}
	YY_BREAK
case 50:
YY_RULE_SETUP
#line 75 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return IF;} /* statements */
	YY_BREAK
case 51:
YY_RULE_SETUP
#line 76 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return ELSE;}
	YY_BREAK
case 52:
YY_RULE_SETUP
#line 77 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return ELSEIF;}
	YY_BREAK
case 53:
YY_RULE_SETUP
#line 78 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return THEN;}
	YY_BREAK
case 54:
YY_RULE_SETUP
#line 79 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return ENDIF;}
	YY_BREAK
case 55:
YY_RULE_SETUP
#line 80 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return DO;}
	YY_BREAK
case 56:
YY_RULE_SETUP
#line 81 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return ENDDO;}
	YY_BREAK
case 57:
YY_RULE_SETUP
#line 82 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return WHILE;}
	YY_BREAK
case 58:
YY_RULE_SETUP
#line 83 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return BREAK;}
	YY_BREAK
case 59:
YY_RULE_SETUP
#line 84 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return CONTINUE;}
	YY_BREAK
case 60:
YY_RULE_SETUP
#line 85 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return RETURN;}
	YY_BREAK
case 61:
YY_RULE_SETUP
#line 86 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return FUNCTION;}
	YY_BREAK
case 62:
YY_RULE_SETUP
#line 87 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return SUBROUTINE;}
	YY_BREAK
case 63:
YY_RULE_SETUP
#line 88 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return CALL;}
	YY_BREAK
case 64:
YY_RULE_SETUP
#line 89 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return GOTO;}
	YY_BREAK
case 65:
YY_RULE_SETUP
#line 90 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return STOP;}
	YY_BREAK
case 66:
YY_RULE_SETUP
#line 91 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return PAUSE;}
	YY_BREAK
/* input / output */
case 67:
YY_RULE_SETUP
#line 93 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return FORMAT;}
	YY_BREAK
case 68:
YY_RULE_SETUP
#line 94 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return WRITE;}
	YY_BREAK
case 69:
YY_RULE_SETUP
#line 95 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return READ;}
	YY_BREAK
case 70:
YY_RULE_SETUP
#line 96 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return PRINT;}
	YY_BREAK
case 71:
YY_RULE_SETUP
#line 97 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return OPEN;}
	YY_BREAK
case 72:
YY_RULE_SETUP
#line 98 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return CLOSE;}
	YY_BREAK
case 73:
YY_RULE_SETUP
#line 99 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return AFILE;}
	YY_BREAK
/* main program units */
case 74:
YY_RULE_SETUP
#line 101 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return PROGRAM;}
	YY_BREAK
case 75:
YY_RULE_SETUP
#line 102 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{return END;}
	YY_BREAK
case 76:
YY_RULE_SETUP
#line 103 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{yylval._str = string(strdup(yytext)); return SYMNAME;}
	YY_BREAK
/*tabs and space*/
case 77:
YY_RULE_SETUP
#line 105 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{}
	YY_BREAK
case 78:
YY_RULE_SETUP
#line 106 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{}
	YY_BREAK
/*end of file*/
case YY_STATE_EOF(INITIAL):
case YY_STATE_EOF(STMT):
#line 108 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{ BEGIN(PROGRAM_ENDS); return END_OF_FILE; }
	YY_BREAK
case YY_STATE_EOF(PROGRAM_ENDS):
#line 109 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
{ return 0; }
	YY_BREAK
case 79:
YY_RULE_SETUP
#line 110 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"
ECHO;
	YY_BREAK
#line 1477 "/home/danil/CLionProjects/F77Ccompiler/src/f77lexer.c"

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - (yytext_ptr)) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = (yy_hold_char);
		YY_RESTORE_YY_MORE_OFFSET

		if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between YY_CURRENT_BUFFER and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
			YY_CURRENT_BUFFER_LVALUE->yy_input_file = yyin;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( (yy_c_buf_p) <= &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			(yy_c_buf_p) = (yytext_ptr) + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state(  );

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = (yytext_ptr) + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++(yy_c_buf_p);
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = (yy_c_buf_p);
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer(  ) )
			{
			case EOB_ACT_END_OF_FILE:
				{
				(yy_did_buffer_switch_on_eof) = 0;

				if ( yywrap(  ) )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					(yy_c_buf_p) = (yytext_ptr) + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				(yy_c_buf_p) =
					(yytext_ptr) + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				(yy_c_buf_p) =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)];

				yy_current_state = yy_get_previous_state(  );

				yy_cp = (yy_c_buf_p);
				yy_bp = (yytext_ptr) + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of user's declarations */
} /* end of yylex */

/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */
static int yy_get_next_buffer (void)
{
    	char *dest = YY_CURRENT_BUFFER_LVALUE->yy_ch_buf;
	char *source = (yytext_ptr);
	int number_to_move, i;
	int ret_val;

	if ( (yy_c_buf_p) > &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( YY_CURRENT_BUFFER_LVALUE->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( (yy_c_buf_p) - (yytext_ptr) - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) ((yy_c_buf_p) - (yytext_ptr) - 1);

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( YY_CURRENT_BUFFER_LVALUE->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars) = 0;

	else
		{
			int num_to_read =
			YY_CURRENT_BUFFER_LVALUE->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = YY_CURRENT_BUFFER_LVALUE;

			int yy_c_buf_p_offset =
				(int) ((yy_c_buf_p) - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yyrealloc( (void *) b->yy_ch_buf,
							 (yy_size_t) (b->yy_buf_size + 2)  );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = NULL;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			(yy_c_buf_p) = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = YY_CURRENT_BUFFER_LVALUE->yy_buf_size -
						number_to_move - 1;

			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move]),
			(yy_n_chars), num_to_read );

		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	if ( (yy_n_chars) == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin  );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			YY_CURRENT_BUFFER_LVALUE->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	if (((yy_n_chars) + number_to_move) > YY_CURRENT_BUFFER_LVALUE->yy_buf_size) {
		/* Extend the array by 50%, plus the number we really need. */
		int new_size = (yy_n_chars) + number_to_move + ((yy_n_chars) >> 1);
		YY_CURRENT_BUFFER_LVALUE->yy_ch_buf = (char *) yyrealloc(
			(void *) YY_CURRENT_BUFFER_LVALUE->yy_ch_buf, (yy_size_t) new_size  );
		if ( ! YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			YY_FATAL_ERROR( "out of dynamic memory in yy_get_next_buffer()" );
		/* "- 2" to take care of EOB's */
		YY_CURRENT_BUFFER_LVALUE->yy_buf_size = (int) (new_size - 2);
	}

	(yy_n_chars) += number_to_move;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] = YY_END_OF_BUFFER_CHAR;
	YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars) + 1] = YY_END_OF_BUFFER_CHAR;

	(yytext_ptr) = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[0];

	return ret_val;
}

/* yy_get_previous_state - get the state just before the EOB char was reached */

    static yy_state_type yy_get_previous_state (void)
{
	yy_state_type yy_current_state;
	char *yy_cp;
    
	yy_current_state = (yy_start);

	for ( yy_cp = (yytext_ptr) + YY_MORE_ADJ; yy_cp < (yy_c_buf_p); ++yy_cp )
		{
		YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			(yy_last_accepting_state) = yy_current_state;
			(yy_last_accepting_cpos) = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 326 )
				yy_c = yy_meta[yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
		}

	return yy_current_state;
}

/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */
    static yy_state_type yy_try_NUL_trans  (yy_state_type yy_current_state )
{
	int yy_is_jam;
    	char *yy_cp = (yy_c_buf_p);

	YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		(yy_last_accepting_state) = yy_current_state;
		(yy_last_accepting_cpos) = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 326 )
			yy_c = yy_meta[yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + yy_c];
	yy_is_jam = (yy_current_state == 325);

		return yy_is_jam ? 0 : yy_current_state;
}

#ifndef YY_NO_UNPUT

    static void yyunput (int c, char * yy_bp )
{
	char *yy_cp;
    
    yy_cp = (yy_c_buf_p);

	/* undo effects of setting up yytext */
	*yy_cp = (yy_hold_char);

	if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		int number_to_move = (yy_n_chars) + 2;
		char *dest = &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[
					YY_CURRENT_BUFFER_LVALUE->yy_buf_size + 2];
		char *source =
				&YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[number_to_move];

		while ( source > YY_CURRENT_BUFFER_LVALUE->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars =
			(yy_n_chars) = (int) YY_CURRENT_BUFFER_LVALUE->yy_buf_size;

		if ( yy_cp < YY_CURRENT_BUFFER_LVALUE->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;

    if ( c == '\n' ){
        --yylineno;
    }

	(yytext_ptr) = yy_bp;
	(yy_hold_char) = *yy_cp;
	(yy_c_buf_p) = yy_cp;
}

#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
    static int yyinput (void)
#else
    static int input  (void)
#endif

{
	int c;
    
	*(yy_c_buf_p) = (yy_hold_char);

	if ( *(yy_c_buf_p) == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( (yy_c_buf_p) < &YY_CURRENT_BUFFER_LVALUE->yy_ch_buf[(yy_n_chars)] )
			/* This was really a NUL. */
			*(yy_c_buf_p) = '\0';

		else
			{ /* need more input */
			int offset = (int) ((yy_c_buf_p) - (yytext_ptr));
			++(yy_c_buf_p);

			switch ( yy_get_next_buffer(  ) )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/*FALLTHROUGH*/

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap(  ) )
						return 0;

					if ( ! (yy_did_buffer_switch_on_eof) )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					(yy_c_buf_p) = (yytext_ptr) + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) (yy_c_buf_p);	/* cast for 8-bit char's */
	*(yy_c_buf_p) = '\0';	/* preserve yytext */
	(yy_hold_char) = *++(yy_c_buf_p);

	if ( c == '\n' )
		
    yylineno++;
;

	return c;
}
#endif	/* ifndef YY_NO_INPUT */

/** Immediately switch to a different input stream.
 * @param input_file A readable stream.
 * 
 * @note This function does not reset the start condition to @c INITIAL .
 */
    void yyrestart  (FILE * input_file )
{
    
	if ( ! YY_CURRENT_BUFFER ){
        yyensure_buffer_stack ();
		YY_CURRENT_BUFFER_LVALUE =
            yy_create_buffer( yyin, YY_BUF_SIZE );
	}

	yy_init_buffer( YY_CURRENT_BUFFER, input_file );
	yy_load_buffer_state(  );
}

/** Switch to a different input buffer.
 * @param new_buffer The new input buffer.
 * 
 */
    void yy_switch_to_buffer  (YY_BUFFER_STATE  new_buffer )
{
    
	/* TODO. We should be able to replace this entire function body
	 * with
	 *		yypop_buffer_state();
	 *		yypush_buffer_state(new_buffer);
     */
	yyensure_buffer_stack ();
	if ( YY_CURRENT_BUFFER == new_buffer )
		return;

	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	YY_CURRENT_BUFFER_LVALUE = new_buffer;
	yy_load_buffer_state(  );

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	(yy_did_buffer_switch_on_eof) = 1;
}

static void yy_load_buffer_state  (void)
{
    	(yy_n_chars) = YY_CURRENT_BUFFER_LVALUE->yy_n_chars;
	(yytext_ptr) = (yy_c_buf_p) = YY_CURRENT_BUFFER_LVALUE->yy_buf_pos;
	yyin = YY_CURRENT_BUFFER_LVALUE->yy_input_file;
	(yy_hold_char) = *(yy_c_buf_p);
}

/** Allocate and initialize an input buffer state.
 * @param file A readable stream.
 * @param size The character buffer size in bytes. When in doubt, use @c YY_BUF_SIZE.
 * 
 * @return the allocated buffer state.
 */
    YY_BUFFER_STATE yy_create_buffer  (FILE * file, int  size )
{
	YY_BUFFER_STATE b;
    
	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yyalloc( (yy_size_t) (b->yy_buf_size + 2)  );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
}

/** Destroy the buffer.
 * @param b a buffer created with yy_create_buffer()
 * 
 */
    void yy_delete_buffer (YY_BUFFER_STATE  b )
{
    
	if ( ! b )
		return;

	if ( b == YY_CURRENT_BUFFER ) /* Not sure if we should pop here. */
		YY_CURRENT_BUFFER_LVALUE = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yyfree( (void *) b->yy_ch_buf  );

	yyfree( (void *) b  );
}

/* Initializes or reinitializes a buffer.
 * This function is sometimes called more than once on the same buffer,
 * such as during a yyrestart() or at EOF.
 */
    static void yy_init_buffer  (YY_BUFFER_STATE  b, FILE * file )

{
	int oerrno = errno;
    
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

    /* If b is the current buffer, then yy_init_buffer was _probably_
     * called from yyrestart() or through yy_get_next_buffer.
     * In that case, we don't want to reset the lineno or column.
     */
    if (b != YY_CURRENT_BUFFER){
        b->yy_bs_lineno = 1;
        b->yy_bs_column = 0;
    }

        b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
    
	errno = oerrno;
}

/** Discard all buffered characters. On the next scan, YY_INPUT will be called.
 * @param b the buffer state to be flushed, usually @c YY_CURRENT_BUFFER.
 * 
 */
    void yy_flush_buffer (YY_BUFFER_STATE  b )
{
    	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == YY_CURRENT_BUFFER )
		yy_load_buffer_state(  );
}

/** Pushes the new state onto the stack. The new state becomes
 *  the current state. This function will allocate the stack
 *  if necessary.
 *  @param new_buffer The new state.
 *  
 */
void yypush_buffer_state (YY_BUFFER_STATE new_buffer )
{
    	if (new_buffer == NULL)
		return;

	yyensure_buffer_stack();

	/* This block is copied from yy_switch_to_buffer. */
	if ( YY_CURRENT_BUFFER )
		{
		/* Flush out information for old buffer. */
		*(yy_c_buf_p) = (yy_hold_char);
		YY_CURRENT_BUFFER_LVALUE->yy_buf_pos = (yy_c_buf_p);
		YY_CURRENT_BUFFER_LVALUE->yy_n_chars = (yy_n_chars);
		}

	/* Only push if top exists. Otherwise, replace top. */
	if (YY_CURRENT_BUFFER)
		(yy_buffer_stack_top)++;
	YY_CURRENT_BUFFER_LVALUE = new_buffer;

	/* copied from yy_switch_to_buffer. */
	yy_load_buffer_state(  );
	(yy_did_buffer_switch_on_eof) = 1;
}

/** Removes and deletes the top of the stack, if present.
 *  The next element becomes the new top.
 *  
 */
void yypop_buffer_state (void)
{
    	if (!YY_CURRENT_BUFFER)
		return;

	yy_delete_buffer(YY_CURRENT_BUFFER );
	YY_CURRENT_BUFFER_LVALUE = NULL;
	if ((yy_buffer_stack_top) > 0)
		--(yy_buffer_stack_top);

	if (YY_CURRENT_BUFFER) {
		yy_load_buffer_state(  );
		(yy_did_buffer_switch_on_eof) = 1;
	}
}

/* Allocates the stack if it does not exist.
 *  Guarantees space for at least one push.
 */
static void yyensure_buffer_stack (void)
{
	yy_size_t num_to_alloc;
    
	if (!(yy_buffer_stack)) {

		/* First allocation is just for 2 elements, since we don't know if this
		 * scanner will even need a stack. We use 2 instead of 1 to avoid an
		 * immediate realloc on the next call.
         */
      num_to_alloc = 1; /* After all that talk, this was set to 1 anyways... */
		(yy_buffer_stack) = (struct yy_buffer_state**)yyalloc
								(num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		memset((yy_buffer_stack), 0, num_to_alloc * sizeof(struct yy_buffer_state*));

		(yy_buffer_stack_max) = num_to_alloc;
		(yy_buffer_stack_top) = 0;
		return;
	}

	if ((yy_buffer_stack_top) >= ((yy_buffer_stack_max)) - 1){

		/* Increase the buffer to prepare for a possible push. */
		yy_size_t grow_size = 8 /* arbitrary grow size */;

		num_to_alloc = (yy_buffer_stack_max) + grow_size;
		(yy_buffer_stack) = (struct yy_buffer_state**)yyrealloc
								((yy_buffer_stack),
								num_to_alloc * sizeof(struct yy_buffer_state*)
								);
		if ( ! (yy_buffer_stack) )
			YY_FATAL_ERROR( "out of dynamic memory in yyensure_buffer_stack()" );

		/* zero only the new slots.*/
		memset((yy_buffer_stack) + (yy_buffer_stack_max), 0, grow_size * sizeof(struct yy_buffer_state*));
		(yy_buffer_stack_max) = num_to_alloc;
	}
}

/** Setup the input buffer state to scan directly from a user-specified character buffer.
 * @param base the character buffer
 * @param size the size in bytes of the character buffer
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_buffer  (char * base, yy_size_t  size )
{
	YY_BUFFER_STATE b;
    
	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return NULL;

	b = (YY_BUFFER_STATE) yyalloc( sizeof( struct yy_buffer_state )  );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = (int) (size - 2);	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = NULL;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b  );

	return b;
}

/** Setup the input buffer state to scan a string. The next call to yylex() will
 * scan from a @e copy of @a str.
 * @param yystr a NUL-terminated string to scan
 * 
 * @return the newly allocated buffer state object.
 * @note If you want to scan bytes that may contain NUL values, then use
 *       yy_scan_bytes() instead.
 */
YY_BUFFER_STATE yy_scan_string (const char * yystr )
{
    
	return yy_scan_bytes( yystr, (int) strlen(yystr) );
}

/** Setup the input buffer state to scan the given bytes. The next call to yylex() will
 * scan from a @e copy of @a bytes.
 * @param yybytes the byte buffer to scan
 * @param _yybytes_len the number of bytes in the buffer pointed to by @a bytes.
 * 
 * @return the newly allocated buffer state object.
 */
YY_BUFFER_STATE yy_scan_bytes  (const char * yybytes, int  _yybytes_len )
{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;
    
	/* Get memory for full buffer, including space for trailing EOB's. */
	n = (yy_size_t) (_yybytes_len + 2);
	buf = (char *) yyalloc( n  );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < _yybytes_len; ++i )
		buf[i] = yybytes[i];

	buf[_yybytes_len] = buf[_yybytes_len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
}

    static void yy_push_state (int  _new_state )
{
    	if ( (yy_start_stack_ptr) >= (yy_start_stack_depth) )
		{
		yy_size_t new_size;

		(yy_start_stack_depth) += YY_START_STACK_INCR;
		new_size = (yy_size_t) (yy_start_stack_depth) * sizeof( int );

		if ( ! (yy_start_stack) )
			(yy_start_stack) = (int *) yyalloc( new_size  );

		else
			(yy_start_stack) = (int *) yyrealloc(
					(void *) (yy_start_stack), new_size  );

		if ( ! (yy_start_stack) )
			YY_FATAL_ERROR( "out of memory expanding start-condition stack" );
		}

	(yy_start_stack)[(yy_start_stack_ptr)++] = YY_START;

	BEGIN(_new_state);
}

    static void yy_pop_state  (void)
{
    	if ( --(yy_start_stack_ptr) < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN((yy_start_stack)[(yy_start_stack_ptr)]);
}

    static int yy_top_state  (void)
{
    	return (yy_start_stack)[(yy_start_stack_ptr) - 1];
}

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

static void yynoreturn yy_fatal_error (const char* msg )
{
			fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
}

/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
        int yyless_macro_arg = (n); \
        YY_LESS_LINENO(yyless_macro_arg);\
		yytext[yyleng] = (yy_hold_char); \
		(yy_c_buf_p) = yytext + yyless_macro_arg; \
		(yy_hold_char) = *(yy_c_buf_p); \
		*(yy_c_buf_p) = '\0'; \
		yyleng = yyless_macro_arg; \
		} \
	while ( 0 )

/* Accessor  methods (get/set functions) to struct members. */

/** Get the current line number.
 * 
 */
int yyget_lineno  (void)
{
    
    return yylineno;
}

/** Get the input stream.
 * 
 */
FILE *yyget_in  (void)
{
        return yyin;
}

/** Get the output stream.
 * 
 */
FILE *yyget_out  (void)
{
        return yyout;
}

/** Get the length of the current token.
 * 
 */
int yyget_leng  (void)
{
        return yyleng;
}

/** Get the current token.
 * 
 */

char *yyget_text  (void)
{
        return yytext;
}

/** Set the current line number.
 * @param _line_number line number
 * 
 */
void yyset_lineno (int  _line_number )
{
    
    yylineno = _line_number;
}

/** Set the input stream. This does not discard the current
 * input buffer.
 * @param _in_str A readable stream.
 * 
 * @see yy_switch_to_buffer
 */
void yyset_in (FILE *  _in_str )
{
        yyin = _in_str ;
}

void yyset_out (FILE *  _out_str )
{
        yyout = _out_str ;
}

int yyget_debug  (void)
{
        return yy_flex_debug;
}

void yyset_debug (int  _bdebug )
{
        yy_flex_debug = _bdebug ;
}

static int yy_init_globals (void)
{
        /* Initialization is the same as for the non-reentrant scanner.
     * This function is called from yylex_destroy(), so don't allocate here.
     */

    /* We do not touch yylineno unless the option is enabled. */
    yylineno =  1;
    
    (yy_buffer_stack) = NULL;
    (yy_buffer_stack_top) = 0;
    (yy_buffer_stack_max) = 0;
    (yy_c_buf_p) = NULL;
    (yy_init) = 0;
    (yy_start) = 0;

    (yy_start_stack_ptr) = 0;
    (yy_start_stack_depth) = 0;
    (yy_start_stack) =  NULL;

/* Defined in main.c */
#ifdef YY_STDINIT
    yyin = stdin;
    yyout = stdout;
#else
    yyin = NULL;
    yyout = NULL;
#endif

    /* For future reference: Set errno on error, since we are called by
     * yylex_init()
     */
    return 0;
}

/* yylex_destroy is for both reentrant and non-reentrant scanners. */
int yylex_destroy  (void)
{
    
    /* Pop the buffer stack, destroying each element. */
	while(YY_CURRENT_BUFFER){
		yy_delete_buffer( YY_CURRENT_BUFFER  );
		YY_CURRENT_BUFFER_LVALUE = NULL;
		yypop_buffer_state();
	}

	/* Destroy the stack itself. */
	yyfree((yy_buffer_stack) );
	(yy_buffer_stack) = NULL;

    /* Destroy the start condition stack. */
        yyfree( (yy_start_stack)  );
        (yy_start_stack) = NULL;

    /* Reset the globals. This is important in a non-reentrant scanner so the next time
     * yylex() is called, initialization will occur. */
    yy_init_globals( );

    return 0;
}

/*
 * Internal utility routines.
 */

#ifndef yytext_ptr
static void yy_flex_strncpy (char* s1, const char * s2, int n )
{
		
	int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
}
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen (const char * s )
{
	int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
}
#endif

void *yyalloc (yy_size_t  size )
{
			return malloc(size);
}

void *yyrealloc  (void * ptr, yy_size_t  size )
{
		
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return realloc(ptr, size);
}

void yyfree (void * ptr )
{
			free( (char *) ptr );	/* see yyrealloc() for (char *) cast */
}

#define YYTABLES_NAME "yytables"

#line 110 "/home/danil/CLionProjects/F77Ccompiler/f77lexer.l"

